import { Driver, Vehicle, Product, ActiveAsset, User } from './types';

export const DEFAULT_DRIVERS: Driver[] = [
  { id: 'G1034', name: 'EDENILSON DE SOUSA SILVA', role: 'MOTORISTA', cpf: '104.695.814-33' },
  { id: 'G1049', name: 'VALDKLEBER DE SOUZA ALEXANDRE', role: 'MOTORISTA', cpf: '058.129.184-06' },
  { id: 'G1019', name: 'DANILLO PEREIRA DOS SANTOS SILVA', role: 'MOTORISTA', cpf: '713.650.714-64' },
  { id: 'G1020', name: 'EWERTON RODRIGUES DA SILVA', role: 'MOTORISTA', cpf: '116.515.224-05' },
  { id: 'G1053', name: 'ADELSON SANTOS DE ARAUJO', role: 'MOTORISTA', cpf: '101.598.524-63' },
  { id: 'G1059', name: 'GILMAR DOS SANTOS FERNANDES', role: 'MOTORISTA', cpf: '058.142.584-70' },
  { id: 'G1076', name: 'MANOEL ALVES DUTRA NETO', role: 'MOTORISTA', cpf: '095.438.274-94' },
  { id: 'G1082', name: 'CESARIO FERREIRA DE VASCONCELOS', role: 'MOTORISTA', cpf: '032.354.034-18' },
  { id: 'G1101', name: 'JOSE HONORIO DA SILVA', role: 'MOTORISTA', cpf: '111.327.744-03' },
  { id: 'G1102', name: 'JOSENILSON INACIO DE ANDRADE', role: 'MOTORISTA', cpf: '098.104.994-00' },
  { id: 'G1104', name: 'JOSE CARLOS DE LIMA ARAUJO', role: 'MOTORISTA', cpf: '122.277.104-70' },
  { id: 'G1111', name: 'EDILSON DE ANDRADE LIMA JUNIOR', role: 'MOTORISTA', cpf: '068.171.834-05' },
  { id: 'G1122', name: 'JEFFERSON JONES PAULINO COSTA', role: 'MOTORISTA', cpf: '071.317.444-76' },
  { id: 'G1140', name: 'JOSE MATUZALEM PONTES DE OLIVEIRA', role: 'MOTORISTA', cpf: '702.136.704-02' },
  { id: 'G1143', name: 'JOSICLAUDIO DE OLIVEIRA RODRIGUES', role: 'MOTORISTA', cpf: '011.689.864-00' },
  { id: 'G1162', name: 'THIAGO JOSE SANTINO DOS SANTOS', role: 'MOTORISTA', cpf: '061.720.027-08' },
  
  // Ajudantes
  { id: 'G1037', name: 'GEOVANE ARAUJO DA SILVA', role: 'AJUDANTE', cpf: '099.123.694-75' },
  { id: 'G1058', name: 'FELIPE GOMES DA SILVA', role: 'AJUDANTE', cpf: '700.552.584-17' },
  { id: 'G1066', name: 'VITOR MACENA GOMES', role: 'AJUDANTE', cpf: '705.138.374-42' },
  { id: 'G1050', name: 'WALLISON PONTES DA SILVA', role: 'AJUDANTE', cpf: '180.471.404-69' },
  { id: 'G1038', name: 'IDALMO FELIPE DOS SANTOS', role: 'AJUDANTE', cpf: '067.166.734-31' },
  { id: 'G1065', name: 'VALTEIR BATISTA DE OLIVEIRA', role: 'AJUDANTE', cpf: '703.583.194-04' },
  { id: 'G1064', name: 'ROMARIO RODRIGUES DA SILVA', role: 'AJUDANTE', cpf: '125.316.744-38' },
  { id: 'G1054', name: 'CARLOS ALBERTO ROQUE DE OLIVEIRA', role: 'AJUDANTE', cpf: '071.040.024-13' },
  { id: 'G1070', name: 'JEFFERSON SOARES PONTES DA SILVA', role: 'AJUDANTE', cpf: '700.478.734-69' },
  { id: 'G1075', name: 'JOALISON JACINTO DOS SANTOS', role: 'AJUDANTE', cpf: '078.444.084-05' },
  { id: 'G1084', name: 'DANIEL FIRMINO DA SILVA', role: 'AJUDANTE', cpf: '074.441.964-60' },
  { id: 'G1089', name: 'ISAIAS DE OLIVEIRA', role: 'AJUDANTE', cpf: '016.308.564-10' },
  { id: 'G1098', name: 'ALAN JUNIOR MATIAS DA SILVA', role: 'AJUDANTE', cpf: '152.088.094-43' },
  { id: 'G1099', name: 'JOSE DE MESQUITA FABRICIO', role: 'AJUDANTE', cpf: '085.892.124-32' },
  { id: 'G1100', name: 'GERLANDO MOREIRA DE AZEVEDO JUNIOR', role: 'AJUDANTE', cpf: '132.603.344-16' }
];

export const DEFAULT_VEHICLES: Vehicle[] = [
  { plate: 'TOU7F39', capacityPallets: 8 },
  { plate: 'TOZ8B20', capacityPallets: 10 },
  { plate: 'TOZ8B50', capacityPallets: 10 },
  { plate: 'SLB3J76', capacityPallets: 10 },
  { plate: 'SLB4A26', capacityPallets: 10 },
  { plate: 'SLB4A56', capacityPallets: 10 },
  { plate: 'QSK7D92', capacityPallets: 10 },
  { plate: 'RLW0C17', capacityPallets: 6 },
  { plate: 'RLR8G79', capacityPallets: 8 },
  { plate: 'RLU4H49', capacityPallets: 8 },
  { plate: 'OXO0532', capacityPallets: 8 },
  { plate: 'OXO0542', capacityPallets: 8 },
  { plate: 'OXO0552', capacityPallets: 6 },
  { plate: 'OXO0782', capacityPallets: 10 },
  { plate: 'NPR2601', capacityPallets: 10 }
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    "code": "347",
    "description": "SUKITA PET 1L CAIXA C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 30.48,
    "curve": "C"
  },
  {
    "code": "982",
    "description": "SKOL 600ML",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 53.35,
    "curve": "C"
  },
  {
    "code": "1388",
    "description": "SKOL GFA VD 1L 2,99",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 51.44,
    "curve": "C"
  },
  {
    "code": "1743",
    "description": "ANTARCTICA PILSEN GFA VD 1L COM TTC",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 40.76,
    "curve": "C"
  },
  {
    "code": "1745",
    "description": "SKOL LT 269ML SH C15 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 30.91,
    "curve": "C"
  },
  {
    "code": "1898",
    "description": "BRAHMA CHOPP LT 269ML SH C15 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 30.92,
    "curve": "C"
  },
  {
    "code": "2319",
    "description": "GUARANA CHP ANTARCTICA PET 1L CAIXA C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 34.22,
    "curve": "C"
  },
  {
    "code": "2353",
    "description": "GUARANA CHP ANTARCTICA DIET PET 2L CAIXA C/6",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 28.09,
    "curve": "C"
  },
  {
    "code": "2546",
    "description": "ORIGINAL 600ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 61.02,
    "curve": "C"
  },
  {
    "code": "4293",
    "description": "PEPSI BLACK PET 200ML SH C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 12.48,
    "curve": "C"
  },
  {
    "code": "7947",
    "description": "GUARANA CHP ANTARCTICA PET 2,5L CAIXA C/6",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.15,
    "cost": 32.35,
    "curve": "C"
  },
  {
    "code": "7980",
    "description": "GATORADE TANGERINA PET 500ML SIXPACK",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 23.41,
    "curve": "C"
  },
  {
    "code": "8411",
    "description": "GUARANA CHP ANTARCTICA PET 1,5 SHRINK C/6",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.09,
    "cost": 25,
    "curve": "C"
  },
  {
    "code": "9068",
    "description": "SKOL LATA 350ML SH C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 28.52,
    "curve": "C"
  },
  {
    "code": "9069",
    "description": "BRAHMA CHOPP LATA 350ML SH C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 28.51,
    "curve": "C"
  },
  {
    "code": "9081",
    "description": "MALZBIER BRAHMA LATA 350ML SH C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 37.9,
    "curve": "C"
  },
  {
    "code": "9083",
    "description": "SKOL LT 473ML SH C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 37.84,
    "curve": "C"
  },
  {
    "code": "9089",
    "description": "SUKITA LATA 350ML SH C/12 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 20.64,
    "curve": "C"
  },
  {
    "code": "9096",
    "description": "PEPSI COLA LATA 350ML SH C/12 NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 20.03,
    "curve": "C"
  },
  {
    "code": "9795",
    "description": "GUARANA ANTARCTICA ZERO PET 1L CAIXA C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 33.45,
    "curve": "C"
  },
  {
    "code": "10537",
    "description": "BOHEMIA GFA VD 990ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 51.64,
    "curve": "C"
  },
  {
    "code": "13205",
    "description": "SKOL GFA VD 300ML CX C/23",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 39.14,
    "curve": "C"
  },
  {
    "code": "13307",
    "description": "BUDWEISER GFA VD 990ML CX C/12",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 56.96,
    "curve": "C"
  },
  {
    "code": "13486",
    "description": "FUSION PET 1L SH C/06",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 38.58,
    "curve": "C"
  },
  {
    "code": "13566",
    "description": "SKOL BEATS SENSES LT 269ML CX C/8 FRIDGE PACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 29.4,
    "curve": "C"
  },
  {
    "code": "14135",
    "description": "BUDWEISER LATA 473ML SIX-PACK SH C/2 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 38.78,
    "curve": "C"
  },
  {
    "code": "14550",
    "description": "COLORADO APPIA ONE WAY 600ML CX C-12 ARTE",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 133.46,
    "curve": "C"
  },
  {
    "code": "16503",
    "description": "BOHEMIA GFA VD 300ML CX C/23",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 38.28,
    "curve": "C"
  },
  {
    "code": "17266",
    "description": "BOHEMIA LT 473ML CX CARTAO C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 73,
    "curve": "C"
  },
  {
    "code": "17757",
    "description": "BECKS N LONG NECK 330ML SIX-PACK SHRINK C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 98.82,
    "curve": "C"
  },
  {
    "code": "17808",
    "description": "BUDWEISER OW 330ML CX C/24",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 90.67,
    "curve": "C"
  },
  {
    "code": "18152",
    "description": "GUARANA CHP ANTARCTICA PET 200ML SH C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 13.21,
    "curve": "C"
  },
  {
    "code": "18266",
    "description": "PEPSI COLA PET 200ML SH C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 12.08,
    "curve": "C"
  },
  {
    "code": "18267",
    "description": "SODA LIMONADA ANTARCTICA PET 200ML SH C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 12.24,
    "curve": "C"
  },
  {
    "code": "18268",
    "description": "SUKITA PET 200ML SH C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 12.47,
    "curve": "C"
  },
  {
    "code": "18752",
    "description": "PATAGONIA WEISSE NACIONAL ONE WAY 740ML CX6",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 71.96,
    "curve": "C"
  },
  {
    "code": "18772",
    "description": "PATAGONIA AMB LAG NACIONAL ONE WAY 740ML CX6",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 71.96,
    "curve": "C"
  },
  {
    "code": "18780",
    "description": "CORONITA EXTRA N OW 210ML CX C/4 SIX PACK",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.05,
    "cost": 83.63,
    "curve": "C"
  },
  {
    "code": "18807",
    "description": "STELLA ARTOIS LONG NECK 330ML SIX-PACK SHRINK C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 101.72,
    "curve": "C"
  },
  {
    "code": "18836",
    "description": "CORONA EXTRA N LONG NECK 330ML CX C/24 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 118.01,
    "curve": "C"
  },
  {
    "code": "19164",
    "description": "GUARANA CHP ANTARCTICA PET 1L PACK C/2 MULTPACK",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 3.9,
    "curve": "C"
  },
  {
    "code": "19166",
    "description": "COLORADO LAGER ONE WAY 600ML CX C-12 ARTE",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 112.88,
    "curve": "C"
  },
  {
    "code": "19225",
    "description": "RED BULL BR LATA 250ML CX C 24 NPAL .",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 138.15,
    "curve": "C"
  },
  {
    "code": "19227",
    "description": "RED BULL BR LATA 355ML FOUR PACK .",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 29.08,
    "curve": "C"
  },
  {
    "code": "19229",
    "description": "RED BULL BR LATA 250ML SIX PACK NPAL .",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 37.23,
    "curve": "C"
  },
  {
    "code": "19231",
    "description": "RED BULL SUGAR FREE BR LATA 250ML FOUR PACK NPAL .",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 24.82,
    "curve": "C"
  },
  {
    "code": "19321",
    "description": "GUARANA ANTARCTICA ZERO PET 200ML SH C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 12.84,
    "curve": "C"
  },
  {
    "code": "19668",
    "description": "ORIGINAL LATA 350ML SH C/12 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 37.58,
    "curve": "C"
  },
  {
    "code": "19729",
    "description": "STELLA ARTOIS LT SLEEK 350ML C 8 CX CARTAO",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 28.85,
    "curve": "C"
  },
  {
    "code": "20217",
    "description": "ORIGINAL GFA VD 300ML CX C/23",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 45.94,
    "curve": "C"
  },
  {
    "code": "20329",
    "description": "BRAHMA DUPLO MALTE 600ML",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 54.69,
    "curve": "C"
  },
  {
    "code": "20498",
    "description": "BRAHMA DUPLO MALTE LT SLEEK 350ML SH C 12",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 32.48,
    "curve": "C"
  },
  {
    "code": "20530",
    "description": "STELLA ARTOIS 600 ML",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 64.71,
    "curve": "C"
  },
  {
    "code": "20535",
    "description": "STELLA ARTOIS ONE WAY 600ML CX C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 76.89,
    "curve": "C"
  },
  {
    "code": "20549",
    "description": "BRAHMA DUPLO MALTE GFA VD 300ML CX C/23",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 44.19,
    "curve": "C"
  },
  {
    "code": "20651",
    "description": "CORONA EXTRA N LT SLEEK 350ML C 8 CX CARTAO",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 29.95,
    "curve": "C"
  },
  {
    "code": "21020",
    "description": "BUDWEISER LT SLEEK 350ML CX CART C 12",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 31.78,
    "curve": "C"
  },
  {
    "code": "21119",
    "description": "SKOL BEATS GT LT 269ML CX CARTAO C/8 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 31.27,
    "curve": "C"
  },
  {
    "code": "21441",
    "description": "SUKITA LIMAO PET 2L CAIXA C/6",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 19.02,
    "curve": "C"
  },
  {
    "code": "21530",
    "description": "SMIRNOFF ORIGINAL GARRAFA VIDRO 998ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 30.28,
    "curve": "C"
  },
  {
    "code": "21632",
    "description": "SPATEN N LN 355ML SIXPACK SH C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.09,
    "cost": 94.58,
    "curve": "C"
  },
  {
    "code": "21658",
    "description": "SPATEN N LT SLEEK 350ML CX CART C 12",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 40.16,
    "curve": "C"
  },
  {
    "code": "21666",
    "description": "RED BULL TROPICAL BR LATA 250ML FOUR PACK NPAL .",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 24.82,
    "curve": "C"
  },
  {
    "code": "21668",
    "description": "SPATEN N ONE WAY 600ML CX C/12 NP ARTE",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 70.31,
    "curve": "C"
  },
  {
    "code": "21778",
    "description": "JOHNNIE WALKER RED LABEL GARRAFA VIDRO 750ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 59,
    "curve": "C"
  },
  {
    "code": "21786",
    "description": "MONTILLA CARTA BRANCA GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 22,
    "curve": "C"
  },
  {
    "code": "21787",
    "description": "DREHER GARRAFA VIDRO 900ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 18.51,
    "curve": "C"
  },
  {
    "code": "21955",
    "description": "CHIVAS REGAL 12 ANOS GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 144.81,
    "curve": "C"
  },
  {
    "code": "21973",
    "description": "TRIDENT MELANCIA ENVELOPE 8G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 34.04,
    "curve": "C"
  },
  {
    "code": "21974",
    "description": "TRIDENT TUTTI-FRUTTI ENVELOPE 8G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 34.05,
    "curve": "C"
  },
  {
    "code": "22009",
    "description": "CHICLETE ADAMS HORTELA CAIXINHA 2,8G CX C/100",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 18.65,
    "curve": "C"
  },
  {
    "code": "22027",
    "description": "COLORADO APPIA LT SLEEK 350ML C8 CX CARTAO NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 35,
    "curve": "C"
  },
  {
    "code": "22177",
    "description": "BUDWEISER ZERO LT SLEEK 350ML C 8 CX CARTAO",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 23.1,
    "curve": "C"
  },
  {
    "code": "22180",
    "description": "BUDWEISER ZERO LONG NECK 330ML SIX-PACK SHRINK C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 86.52,
    "curve": "C"
  },
  {
    "code": "22200",
    "description": "TONICA ANTARCTICA PET 1 L SH C/06",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 27.31,
    "curve": "C"
  },
  {
    "code": "22202",
    "description": "TONICA ANTARCTICA ZERO PET 1L SH C/06",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 25.67,
    "curve": "C"
  },
  {
    "code": "22326",
    "description": "BRAHMA DUPLO MALTE LT 473ML SH C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 37.67,
    "curve": "C"
  },
  {
    "code": "22871",
    "description": "PIRAQUE ROLADINHO GOIABA PCT 75G CX C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 120.8,
    "curve": "C"
  },
  {
    "code": "23184",
    "description": "PITU AGUARDENTE LT 350ML CX C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 48.03,
    "curve": "C"
  },
  {
    "code": "23186",
    "description": "SPATEN N 600ML",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 60.57,
    "curve": "C"
  },
  {
    "code": "23256",
    "description": "PIRACANJUBA CREME DE LEITE TETRAPAK 200G CX C/27",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.05,
    "cost": 72.63,
    "curve": "C"
  },
  {
    "code": "23269",
    "description": "SKOL BEATS GT LONG NECK 269ML SIX-PACK SH C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 115.95,
    "curve": "C"
  },
  {
    "code": "23271",
    "description": "SKOL BEATS SENSES LONG NECK 269ML SIX-PACK SH C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 107.11,
    "curve": "C"
  },
  {
    "code": "23546",
    "description": "INDAIA AGUA MINERAL C/GAS GFA PET 500ML PACK C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 16.34,
    "curve": "C"
  },
  {
    "code": "23552",
    "description": "INDAIA AGUA MINERAL S/GAS GFA PET 500ML PACK C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 14.21,
    "curve": "C"
  },
  {
    "code": "23594",
    "description": "PIRAKIDS BEBIDA LACTEA CHOCOLATE TETRA PAK 200 ML CX C/27",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.05,
    "cost": 31.07,
    "curve": "C"
  },
  {
    "code": "24168",
    "description": "MICHELOB ULTRA N LONG NECK 330ML SIX-PACK SHRINK C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 130.86,
    "curve": "C"
  },
  {
    "code": "24256",
    "description": "PETROPOLIS AGUA MIN SEM GAS PET 1,5 SHRINK C/6",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.09,
    "cost": 9.5,
    "curve": "C"
  },
  {
    "code": "24304",
    "description": "TODDYNHO 200ML TETRA PAK 200 ML CX C/27",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.05,
    "cost": 55.56,
    "curve": "C"
  },
  {
    "code": "24306",
    "description": "RED BULL MELANCIA LATA 250ML FOUR PACK NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 23.86,
    "curve": "C"
  },
  {
    "code": "24408",
    "description": "QUINTA DO MORGADO VINHO TINTO SECO GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.77,
    "curve": "C"
  },
  {
    "code": "24409",
    "description": "QUINTA DO MORGADO VINHO TINTO SUAVE GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 14.24,
    "curve": "C"
  },
  {
    "code": "25151",
    "description": "OLD PARR WHISKY GFA VDR 1L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 108.92,
    "curve": "C"
  },
  {
    "code": "25160",
    "description": "BLACK & WHITE WHISKY GFA VDR 1L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 44.51,
    "curve": "C"
  },
  {
    "code": "25194",
    "description": "CACHACA 51 LT 350ML CX C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 29.82,
    "curve": "C"
  },
  {
    "code": "25546",
    "description": "GARRAFEIRA PL. AL. LAT. AB. PRETA BEES 1 UN P/ 23 GFA 300ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 25,
    "curve": "C"
  },
  {
    "code": "25700",
    "description": "FUSION PET 2L SHRINK C/6",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 31.02,
    "curve": "C"
  },
  {
    "code": "25837",
    "description": "SPATEN N LT 473ML CX CARTAO C/12",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 85.9,
    "curve": "C"
  },
  {
    "code": "26037",
    "description": "MONTILLA CARTA CRISTAL GFA VDR 1L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 22.97,
    "curve": "C"
  },
  {
    "code": "26462",
    "description": "ORIGINAL LT 473ML CX CARTAO C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 41.67,
    "curve": "C"
  },
  {
    "code": "27522",
    "description": "CACHACA 51 PIRASSUNUNGA GFA VD 965ML RET CX/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 64.28,
    "curve": "C"
  },
  {
    "code": "27559",
    "description": "CACHACA 51 PIRASSUNUNGA OURO GFA VD 965ML RET CX/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 89.64,
    "curve": "C"
  },
  {
    "code": "27866",
    "description": "CORONA CERO SUNBREW N LONG NECK 330 ML SP BASKET CX C4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 119.8,
    "curve": "C"
  },
  {
    "code": "29197",
    "description": "TANG REFRESCO EM PO LIMAO PCT 18G DP C/18",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.38,
    "curve": "C"
  },
  {
    "code": "29201",
    "description": "TANG REFRESCO EM PO ABACAXI PCT 18G DP C/18",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.38,
    "curve": "C"
  },
  {
    "code": "29207",
    "description": "TANG REFRESCO EM PO MORANGO PCT 18G DP C/18",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.37,
    "curve": "C"
  },
  {
    "code": "29253",
    "description": "ORIGINAL GFA VD 1L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 62.85,
    "curve": "C"
  },
  {
    "code": "29485",
    "description": "SKOL BEATS CAIPIRINHA LONG NECK 269ML SIX-PACK SH C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 122.65,
    "curve": "C"
  },
  {
    "code": "29580",
    "description": "STELLA ARTOIS PURE GOLD LONG NECK 330ML SP SH C/4",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 106.95,
    "curve": "C"
  },
  {
    "code": "29845",
    "description": "PEPSI BLACK PET 1 L SH C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 34.44,
    "curve": "C"
  },
  {
    "code": "30045",
    "description": "RED BULL BR LATA 473ML CX C 12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 96.18,
    "curve": "C"
  },
  {
    "code": "30148",
    "description": "TRELOSO BISCOITO RECHEADO CHOCOLATE PCT 120G CX/36",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 53.28,
    "curve": "C"
  },
  {
    "code": "30151",
    "description": "TRELOSO RECHEADO BAUNILHA CHOCORESCO PCT 120G CX/36",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 53.28,
    "curve": "C"
  },
  {
    "code": "30152",
    "description": "TRELOSO BISCOITO RECHEADO MORANGO PCT 120G CX/36",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 53.28,
    "curve": "C"
  },
  {
    "code": "31064",
    "description": "BUDWEISER LT 269ML SH C 15",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 33.68,
    "curve": "C"
  },
  {
    "code": "31272",
    "description": "FUSION LT 473ML SH C/12 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 45,
    "curve": "C"
  },
  {
    "code": "31582",
    "description": "YPE LAVA LOUCAS LIQUIDO CLEAR FRASCO PLASTICO 500 ML C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 46.1,
    "curve": "C"
  },
  {
    "code": "31589",
    "description": "YPE LAVA LOUCAS LIQUIDO MACA FRASCO PLASTICO 500 ML C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 46.1,
    "curve": "C"
  },
  {
    "code": "31667",
    "description": "YPE LAVA LOUCAS LIQUIDO NEUTRO FRASCO PLASTICO 500 ML C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 46.1,
    "curve": "C"
  },
  {
    "code": "31669",
    "description": "YPE LAVA LOUCAS LIQUIDO COCO FRASCO PLASTICO 500 ML C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 46.1,
    "curve": "C"
  },
  {
    "code": "32036",
    "description": "PIRAQUE MAIZENA PCT PLAST 175G C48",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 94.08,
    "curve": "C"
  },
  {
    "code": "32067",
    "description": "GATORADE BERRY BLUE PET 500ML SIXPACK",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 22.72,
    "curve": "C"
  },
  {
    "code": "32361",
    "description": "BEATS TROPICAL LONG NECK 269ML SIX-PACK SH C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 123.34,
    "curve": "C"
  },
  {
    "code": "32425",
    "description": "FUSION MELANCIA LT 473ML SH C/12 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 51.48,
    "curve": "C"
  },
  {
    "code": "32427",
    "description": "FUSION TROPICAL LT 473ML SH C/12 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 45,
    "curve": "C"
  },
  {
    "code": "32500",
    "description": "STELLA ARTOIS PURE GOLD LT SLEEK 350ML C 8 CX CARTAO",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 30.3,
    "curve": "C"
  },
  {
    "code": "32526",
    "description": "PETROPOLIS AGUA MIN SEM GAS GARRAFA PET 500MLCX C12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 10.58,
    "curve": "C"
  },
  {
    "code": "32528",
    "description": "PETROPOLIS AGUA MIN COM GAS GARRAFA PET 500MLCX C12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 12.17,
    "curve": "C"
  },
  {
    "code": "32644",
    "description": "BUBBALOO UVA DISPLAY 5G CX/60",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 12.44,
    "curve": "C"
  },
  {
    "code": "32646",
    "description": "BUBBALOO TUTTI FRUTTI DISPLAY 5G CX/60",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 12.44,
    "curve": "C"
  },
  {
    "code": "33042",
    "description": "YPE LAVA LOUCAS LIQUIDO LIMAO FRASCO PLASTICO 500 ML C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 46.93,
    "curve": "C"
  },
  {
    "code": "33046",
    "description": "YPE TIXAN LAVA ROUPAS PO MACIEZ SACHE PLASTICO 800G CX20",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.16,
    "cost": 168.4,
    "curve": "C"
  },
  {
    "code": "33048",
    "description": "YPE TIXAN LAVA ROUPAS PO PRIMAV SACHE PLASTICO 800G CX20",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.16,
    "cost": 168.4,
    "curve": "C"
  },
  {
    "code": "33061",
    "description": "YPE TIXAN LAVA ROUPAS PO MACIEZ SACHE 400G CX C/24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.1,
    "cost": 90.06,
    "curve": "C"
  },
  {
    "code": "33066",
    "description": "YPE TIXAN LAVA ROUPAS PO PRIMAV SACHE 400G CX C/24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.1,
    "cost": 90.06,
    "curve": "C"
  },
  {
    "code": "33734",
    "description": "BEATS RED MIX LT 269ML SH C/8",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 35.29,
    "curve": "C"
  },
  {
    "code": "33738",
    "description": "BEATS RED MIX LONG NECK 269ML SIX-PACK SH C/2",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 67.23,
    "curve": "C"
  },
  {
    "code": "33820",
    "description": "BRAHMA CHOPP LATA 350ML SH C/12 NPAL MULTIPACK .",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 34.9,
    "curve": "C"
  },
  {
    "code": "34263",
    "description": "CORONA CERO SUNBREW N LT SLEEK 350ML C 8 CX CARTAO",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 28.21,
    "curve": "C"
  },
  {
    "code": "34296",
    "description": "TRIDENT CANELA ENVELOPE 8G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 31.23,
    "curve": "C"
  },
  {
    "code": "34298",
    "description": "TRIDENT MORANGO ENVELOPE 8G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 31.23,
    "curve": "C"
  },
  {
    "code": "34410",
    "description": "HALLS UVA VERDE ENVELOPE 28G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 30.9,
    "curve": "C"
  },
  {
    "code": "34608",
    "description": "SKOL LATA 350ML SH C/12 NPAL MULTIPACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 39,
    "curve": "C"
  },
  {
    "code": "35003",
    "description": "TRIDENT XFRESH 5S PRETO CEREJA ENVELOPE 8G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 34.04,
    "curve": "C"
  },
  {
    "code": "22562",
    "description": "DOMECQ COQ. COMPOSTO GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 42.19,
    "curve": "C"
  },
  {
    "code": "22813",
    "description": "BUDWEISER LATA 310ML CX C/6 MULTPACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "22815",
    "description": "BRAHMA DUPLO MALTE LATA 310ML CX C/6 MULTPACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "22819",
    "description": "BOHEMIA LATA 310ML CX C/6 MULTPACK 06",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23058",
    "description": "PIRACANJUBA DESNATADO CX 1L CX C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23193",
    "description": "BEATS MOSCOW MULE LT 269ML CX CARTAO C/8 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23194",
    "description": "BEATS MOJITO LT 269ML CX CARTAO C/8 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23246",
    "description": "PIRACANJUBA LEITE CONDENSADO TETRAPAK 395G CX C/27",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.11,
    "cost": 120.96,
    "curve": "C"
  },
  {
    "code": "23440",
    "description": "SALINAS TRAD. CACHACA GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23443",
    "description": "PITU AGUARDENTE GARRAFA VIDRO 965ML",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 9.5,
    "curve": "C"
  },
  {
    "code": "23449",
    "description": "MIKES HARD LEMONADE N LT 269ML SH C12 NP",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 40,
    "curve": "C"
  },
  {
    "code": "23450",
    "description": "MIKES HARD LEMONADE PITAIA N LT 269ML SH C12 NP",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23451",
    "description": "MIKES HARD LEMONADE TANGERINA N LT 269ML SH C12 NP",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "23608",
    "description": "PIRACANJUBA LEITE EM PO INTEGRAL SACO AL. 200G FD C/50",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.1,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "24479",
    "description": "BOHEMIA LONG NECK 330ML SIX-PACK SHRINK C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.08,
    "cost": 78.42,
    "curve": "C"
  },
  {
    "code": "25178",
    "description": "51 ICE LIMAO GARRAFA VD 275ML CX C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 100.48,
    "curve": "C"
  },
  {
    "code": "27177",
    "description": "HALLS MENTOL ENVELOPE 28G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 21.85,
    "curve": "C"
  },
  {
    "code": "27686",
    "description": "MIKES HARD LEMONADE N LONG NECK 275ML SIX PACK SH C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 126.46,
    "curve": "C"
  },
  {
    "code": "27704",
    "description": "MIKES HARD LEMONADE PITAIA N LONG NECK 275ML SIX PACK SH C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 126.76,
    "curve": "C"
  },
  {
    "code": "28137",
    "description": "SKOL BEATS CAIPIRINHA LT 269ML CX CARTAO C/8 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 32.58,
    "curve": "C"
  },
  {
    "code": "28202",
    "description": "BUBBALOO TUTTI FRUTTI DISPLAY 300G",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "28203",
    "description": "BUBBALOO MORANGO DISPLAY 300G",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 11.31,
    "curve": "C"
  },
  {
    "code": "28204",
    "description": "BUBBALOO UVA DISPLAY 300G",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 10.99,
    "curve": "C"
  },
  {
    "code": "29199",
    "description": "TANG REFRESCO EM PO LARANJA PCT 18G DP C/18",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.37,
    "curve": "C"
  },
  {
    "code": "29209",
    "description": "TANG REFRESCO EM PO MARACUJA PCT 18G DP C/18",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.37,
    "curve": "C"
  },
  {
    "code": "29215",
    "description": "TANG REFRESCO EM PO UVA PCT 18G DP C/18",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.37,
    "curve": "C"
  },
  {
    "code": "29323",
    "description": "INDAIA BEB MISTA CITRUS LARANJA GFA PET 330ML FD C/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "25220",
    "description": "CACHACA 51 PIRASS OURO DESCARTAVEL GFA DE VDRO 965ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 12.3,
    "curve": "C"
  },
  {
    "code": "23028",
    "description": "BUCHANANS WHISKY DELUXE 12 ANOS GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 180.86,
    "curve": "C"
  },
  {
    "code": "21526",
    "description": "JOHNNIE WALKER RED LABEL GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 74,
    "curve": "C"
  },
  {
    "code": "26607",
    "description": "RED BULL PITAYA LATA 250ML FOUR PACK NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 25.01,
    "curve": "C"
  },
  {
    "code": "21792",
    "description": "WHITE HORSE GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 62.13,
    "curve": "C"
  },
  {
    "code": "23029",
    "description": "JOHNNIE WALKER BLACK LABEL GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 122.34,
    "curve": "C"
  },
  {
    "code": "26994",
    "description": "SMIRNOFF ORIGINAL GFA VDR 600ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "32122",
    "description": "SMIRNOFF VODKA N21 GFA PET 1,75L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "21788",
    "description": "BALLANTINES FINEST GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 83.39,
    "curve": "C"
  },
  {
    "code": "32349",
    "description": "BEATS TROPICAL LT 269ML CX CARTAO C/8 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 32.12,
    "curve": "C"
  },
  {
    "code": "21781",
    "description": "SMIRNOFF ICE GARRAFA VD 275ML CX C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 154.89,
    "curve": "C"
  },
  {
    "code": "33109",
    "description": "51 OURO AGUARDENTE COMPOSTA LT 350ML CX C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 50.02,
    "curve": "C"
  },
  {
    "code": "30856",
    "description": "BUBBALOO BALA MORANGO DISPLAY 15G CX/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "22003",
    "description": "HALLS CEREJA ENVELOPE 28G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 21.85,
    "curve": "C"
  },
  {
    "code": "21529",
    "description": "ABSOLUT ORIGINAL GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 77.85,
    "curve": "C"
  },
  {
    "code": "9427",
    "description": "ANTARCTICA PILSEN LT 473ML SH C/12 NPAL",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 45.9,
    "curve": "C"
  },
  {
    "code": "20164",
    "description": "SKOL LT 473ML SH C/12 NPAL MULTPACK 12",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 37.4,
    "curve": "C"
  },
  {
    "code": "34027",
    "description": "GUARANA CHP ANTARCTICA LATA 350ML SH C/12 NPAL MULTIPACK",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 30.48,
    "curve": "C"
  },
  {
    "code": "34320",
    "description": "GUARANA ANTARCTICA ZERO LATA 350ML SH C/12 NPAL MULTIPACK",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 35.88,
    "curve": "C"
  },
  {
    "code": "34429",
    "description": "RED BULL SUGAR FREE AMORA LATA 250ML FOUR PACK NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 31.96,
    "curve": "C"
  },
  {
    "code": "34454",
    "description": "H2OH LIMONETO LT SLEEK 350ML SH C 12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 33.6,
    "curve": "C"
  },
  {
    "code": "34475",
    "description": "ELEVE AGUA MIN S GAS GFA PET 510ML FD C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 10.04,
    "curve": "C"
  },
  {
    "code": "34918",
    "description": "DIAS DAVILA AGUA MIN S GAS PET 500ML PACK C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 19.54,
    "curve": "C"
  },
  {
    "code": "34920",
    "description": "DIAS DAVILA AGUA MIN S GAS PET 1,5L FD C/6",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.09,
    "cost": 20.12,
    "curve": "C"
  },
  {
    "code": "35331",
    "description": "BUDWEISER GFA VD 1L",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 65.61,
    "curve": "C"
  },
  {
    "code": "35617",
    "description": "BEATS GREEN MIX LT 269ML SH C/8",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 38.71,
    "curve": "C"
  },
  {
    "code": "36034",
    "description": "BUDWEISER LT 473ML SH C12 NP MULTIPACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 64.88,
    "curve": "C"
  },
  {
    "code": "33818",
    "description": "ORIGINAL LATA 350ML SHRINK C/12 MULTPACK",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 37.58,
    "curve": "C"
  },
  {
    "code": "37450",
    "description": "BUDWEISER LT SLEEK 350ML SH C 12 MULTIPACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 41.69,
    "curve": "C"
  },
  {
    "code": "34479",
    "description": "ELEVE AGUA MIN S GAS PET 1,5 SHRINK C/6",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.09,
    "cost": 13.42,
    "curve": "C"
  },
  {
    "code": "34325",
    "description": "ELEVE AGUA MIN C GAS GFA PET 510ML FD C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 17.9,
    "curve": "C"
  },
  {
    "code": "33857",
    "description": "STELLA ARTOIS PURE GOLD 600ML",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 108,
    "curve": "C"
  },
  {
    "code": "29508",
    "description": "JOHNNIE WALKER WHISKY GOLD LABEL RESERVE GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 201.64,
    "curve": "C"
  },
  {
    "code": "31678",
    "description": "YPE AMACIANTE CONC BLUE GARDEN FRASCO PLAST 1 L CX12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 166,
    "curve": "C"
  },
  {
    "code": "35620",
    "description": "BEATS GREEN MIX LONG NECK 269ML SIX-PACK SH C/4",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 135,
    "curve": "C"
  },
  {
    "code": "32175",
    "description": "CROKISSIMO AMEND CROC LEV SALGADO PCT 24G FD/36",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 127.38,
    "curve": "C"
  },
  {
    "code": "25174",
    "description": "51 ICE BALADA GARRAFA VD 275ML CX C24",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 116,
    "curve": "C"
  },
  {
    "code": "31795",
    "description": "BRUTAL FRUIT LONG NECK 275ML SIX PACK SH C 2",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 103.8,
    "curve": "C"
  },
  {
    "code": "31708",
    "description": "YPE AMACIANTE CONC BLUE GARDEN FRASCO PLAST 500ML CX/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 83.8,
    "curve": "C"
  },
  {
    "code": "35338",
    "description": "BUDWEISER ZERO LT 473ML SH C/12 NPAL",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 55.9,
    "curve": "C"
  },
  {
    "code": "20533",
    "description": "BRAHMA DUPLO MALTE GFA VD 1L",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 55.86,
    "curve": "C"
  },
  {
    "code": "35980",
    "description": "CASAL GARCIA VINHO ROSE GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 53.49,
    "curve": "C"
  },
  {
    "code": "35108",
    "description": "CERVEGELA PLASTICA SPATEN 1 UN P/ GFA 600ML CX3",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.77,
    "curve": "C"
  },
  {
    "code": "27613",
    "description": "CASILLERO DEL DIABLO VNH RSV CABER SAUVG GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.57,
    "curve": "C"
  },
  {
    "code": "35992",
    "description": "CASAL GARCIA VINHO BR VERDE GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51,
    "curve": "C"
  },
  {
    "code": "31674",
    "description": "YPE AMACIANTE INTENSO FRASCO PLASTICO 2 L CX6",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.12,
    "cost": 47.68,
    "curve": "C"
  },
  {
    "code": "25434",
    "description": "MATUTA CACHACA MEL E LIMAO GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 42.8,
    "curve": "C"
  },
  {
    "code": "25329",
    "description": "SALTON ESPUMANTE BRUT GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 40.18,
    "curve": "C"
  },
  {
    "code": "21968",
    "description": "TRIDENT HORTELA ENVELOPE 8G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 34.05,
    "curve": "C"
  },
  {
    "code": "7979",
    "description": "GATORADE FRUTAS CITRICAS PET 500ML SIXPACK",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 28.68,
    "curve": "C"
  },
  {
    "code": "29891",
    "description": "ROCKS DRY GIN GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 24.32,
    "curve": "C"
  },
  {
    "code": "22543",
    "description": "ROCKS STRAMBERRY GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 24.32,
    "curve": "C"
  },
  {
    "code": "1699",
    "description": "STELLA ARTOIS LT 269ML CX C/8 FRIDGE PACK",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 21.95,
    "curve": "C"
  },
  {
    "code": "22005",
    "description": "HALLS MENTA ENVELOPE 28G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 21.85,
    "curve": "C"
  },
  {
    "code": "22007",
    "description": "HALLS EXTRA FORTE ENVELOPE 28G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 21.85,
    "curve": "C"
  },
  {
    "code": "29733",
    "description": "HALLS MELANCIA ENVELOPE 28G CX C/21",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 19.97,
    "curve": "C"
  },
  {
    "code": "24161",
    "description": "S. JOAO BARRA CONHAQUE ALC. GARRAFA VIDRO 900ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 19.3,
    "curve": "C"
  },
  {
    "code": "24488",
    "description": "GALLO AZEITE OLIVA EX. VIR. GFA VDR 250ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 17.21,
    "curve": "C"
  },
  {
    "code": "24410",
    "description": "QUINTA DO MORGADO VINHO BRANCO SUAVE GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 16,
    "curve": "C"
  },
  {
    "code": "35012",
    "description": "MENDORATO PCT 45G DISPLAY C10",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.95,
    "curve": "C"
  },
  {
    "code": "24411",
    "description": "QUINTA DO MORGADO VINHO BRANCO SECO GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 13.77,
    "curve": "C"
  },
  {
    "code": "35136",
    "description": "YPE SABAO BARRA MULTIATIVO PCT PLAST 800G",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 8.95,
    "curve": "C"
  },
  {
    "code": "4262",
    "description": "MICHELOB ULTRA N LT SLEEK 350ML C 8 CX CARTAO",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 32.83,
    "curve": "C"
  },
  {
    "code": "13203",
    "description": "ANTARCTICA PILSEN GFA VD 300ML CX C/23",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.07,
    "cost": 53.9,
    "curve": "C"
  },
  {
    "code": "21527",
    "description": "TANQUERAY GIN LONDON DRY GARRAFA VIDRO 750ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 79.9,
    "curve": "C"
  },
  {
    "code": "22382",
    "description": "PASSPORT SELECTION GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 31.79,
    "curve": "C"
  },
  {
    "code": "23671",
    "description": "CERVEGELA PLASTICA BRAHMA 1 UN P/ GFA 1L CX C/3",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.77,
    "curve": "C"
  },
  {
    "code": "23672",
    "description": "CERVEGELA PLASTICA BRAHMA 1 UN P/ GFA 600ML CX C/3",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.77,
    "curve": "C"
  },
  {
    "code": "24486",
    "description": "GALLO AZEITE OLIVA EX. VIR. GFA VDR 500ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 29.97,
    "curve": "C"
  },
  {
    "code": "24604",
    "description": "MINALBA AGUA PREMIUM C/GAS GFA VDR 300ML CX/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 56.7,
    "curve": "C"
  },
  {
    "code": "24609",
    "description": "MINALBA AGUA PREMIUM S/GAS GFA VDR 300ML CX/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.04,
    "cost": 49,
    "curve": "C"
  },
  {
    "code": "25303",
    "description": "GARRAFEIRA PL. PRETO BEES 1 UN P/24 GFA 600ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 31.16,
    "curve": "C"
  },
  {
    "code": "25335",
    "description": "SALTON ESPUMANTE BRUT ROSE GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 40.18,
    "curve": "C"
  },
  {
    "code": "25347",
    "description": "SALTON ESPUMANTE CLASSIC MOSCATEL GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 40.18,
    "curve": "C"
  },
  {
    "code": "25429",
    "description": "MATUTA CACHACA CRISTAL GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 21.92,
    "curve": "C"
  },
  {
    "code": "25430",
    "description": "MATUTA CACHACA UMBURANA GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 25.28,
    "curve": "C"
  },
  {
    "code": "27560",
    "description": "CASILLERO DEL DIABLO VINH RESERVA MALBEC GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.57,
    "curve": "C"
  },
  {
    "code": "27562",
    "description": "CASILLERO DEL DIABLO VINH RESERVA MERLOT GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.57,
    "curve": "C"
  },
  {
    "code": "27566",
    "description": "RESERVADO VINHO SWEET RED GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 28.81,
    "curve": "C"
  },
  {
    "code": "29416",
    "description": "CERVEGELA BUDWEISER 1 UN P/ GF 600ML CX3",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.02,
    "cost": 51.77,
    "curve": "C"
  },
  {
    "code": "29418",
    "description": "CERVEGELA BUDWEISER LITRAO 1 UN P/ GF 1L PACK C3",
    "group": "CERVEJA",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.03,
    "cost": 51.77,
    "curve": "C"
  },
  {
    "code": "29504",
    "description": "OLD PARR WHISKY 12 ANOS GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 98.9,
    "curve": "C"
  },
  {
    "code": "29505",
    "description": "CIROC VODKA GFA VD 750 ML",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 162.39,
    "curve": "C"
  },
  {
    "code": "29926",
    "description": "JOHNNIE  WALKER BLACK LABEL WHISKY ICONS GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 177.42,
    "curve": "C"
  },
  {
    "code": "31713",
    "description": "YPE AMACIANTE CONC PINK FRASCO PLAST 500ML CX/12",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 86.21,
    "curve": "C"
  },
  {
    "code": "32126",
    "description": "AMINDUS GRELHADITOS AMEND. TOR. S/ PELE PCT 24G FD C/60",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 26.53,
    "curve": "C"
  },
  {
    "code": "32538",
    "description": "PERGOLA SEL. VINHO TINTO SUAVE GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 21.5,
    "curve": "C"
  },
  {
    "code": "32648",
    "description": "BUBBALOO MORANGO DISPLAY 5G CX/60",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 12.44,
    "curve": "C"
  },
  {
    "code": "32969",
    "description": "RED BULL SUMMER MORANGO E PESSEGO LATA 250ML FOUR PACK NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 31.96,
    "curve": "C"
  },
  {
    "code": "33854",
    "description": "YPE TIXAN LAVA ROUPAS LIQ PRIMAVERA FRASCO PLAST 1L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 120.6,
    "curve": "C"
  },
  {
    "code": "34420",
    "description": "RED BULL SUMMER MARACUJA E MELAO LATA 250ML FOUR PACK NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 29.16,
    "curve": "C"
  },
  {
    "code": "34432",
    "description": "RED BULL TROPICAL BR LATA 473ML CX C 12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 140.44,
    "curve": "C"
  },
  {
    "code": "34770",
    "description": "RED BULL SUGAR FREE POMELO LATA 250ML FOUR PACK NPAL",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 31.96,
    "curve": "C"
  },
  {
    "code": "34923",
    "description": "DIAS DAVILA AGUA MINERAL C GAS GFA PET 500ML PACK C/12",
    "group": "NAB",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.06,
    "cost": 19.59,
    "curve": "C"
  },
  {
    "code": "37576",
    "description": "DOCES VIEIRA PE DE MOCA PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 40.91,
    "curve": "C"
  },
  {
    "code": "37579",
    "description": "DOCES VIEIRA BEIJO DE LEITE PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.03,
    "curve": "C"
  },
  {
    "code": "37580",
    "description": "DOCES VIEIRA CHURRITOS PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 48.9,
    "curve": "C"
  },
  {
    "code": "37581",
    "description": "DOCES VIEIRA COCADA BAIANA PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 51.03,
    "curve": "C"
  },
  {
    "code": "37582",
    "description": "DOCES VIEIRA COCADA BRANCA PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 48.9,
    "curve": "C"
  },
  {
    "code": "37583",
    "description": "DOCES VIEIRA BEIJO DE MOCA PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "37933",
    "description": "DOCES VIEIRA BRIGADEIRO PCT PLAST 23G POTE C/40",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 48.9,
    "curve": "C"
  },
  {
    "code": "25433",
    "description": "MATUTA CACHACA COCO GARRAFA VIDRO 1 L",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 0,
    "curve": "C"
  },
  {
    "code": "35134",
    "description": "YPE SABAO BARRA NEUTRO PCT PLAST 800G",
    "group": "MARKETPLACE",
    "unit": "un",
    "palletFactor": 84,
    "skuFactor": 1,
    "hectoFactor": 0.01,
    "cost": 8.95,
    "curve": "C"
  }
];

export const DEFAULT_ACTIVE_ASSETS: ActiveAsset[] = [
  { id: '188005', name: 'GARRAFEIRA 1L', category: 'GARRAFEIRA', cost: 35.00 },
  { id: '899599', name: 'GARRAFEIRA 600ML', category: 'GARRAFEIRA', cost: 31.16 },
  { id: '863059', name: 'GARRAFEIRA 300ML', category: 'GARRAFEIRA', cost: 25.00 },
  { id: '786238', name: 'GARRAFA VERDE 600ML (RET)', category: 'GARRAFA', cost: 2.50 },
  { id: '27983', name: 'GARRAFA 600 ÂMBAR (RET)', category: 'GARRAFA', cost: 2.20 },
  { id: '188006', name: 'GARRAFA 1L(RET)', category: 'GARRAFA', cost: 3.50 },
  { id: '198214', name: 'GARRAFA 300ML (RET)', category: 'GARRAFA', cost: 1.50 },
  { id: 'pal_pbr', name: 'PALETE PBR', category: 'PALETE', cost: 120.00 },
  { id: 'chapatex', name: 'CHAPATEX', category: 'OUTRO', cost: 18.00 }
];

export const DEFAULT_USERS: User[] = [
  { id: 'usr_g1009', name: 'Administrador G1009', role: 'gestor', username: 'G1009', password: '123' },
  { id: 'usr_1782482189381', name: 'ELISSON MINERVINO', role: 'gestor', username: '7224', password: '123' },
  { id: 'usr_1782482208921', name: 'MARCOS GUILHERME', role: 'gestor', username: '7171', password: '123' },
  { id: 'usr_1782481995449', name: 'GLADSON LISBOA', role: 'conferente', username: 'g1145', password: '123' },
  { id: 'usr_1782482023049', name: 'GILSON ROSA', role: 'conferente', username: 'g1088', password: '123' },
  { id: 'usr_1782482081189', name: 'ALÉCYA FERREIRA', role: 'auxiliar_logistica', username: 'G1163', password: 'Ambev10' },
  { id: 'usr_1782482101263', name: 'DJEANDERSON SOARES', role: 'gestor', username: 'G1002', password: '!Liz1105' },
  { id: 'usr_1782482138597', name: 'VICTOR MARINHO', role: 'gestor', username: 'g1083', password: '123' },
  { id: 'usr_1782482170529', name: 'LUIZ EDUARDO', role: 'gestor', username: 'g1149', password: '123' },
  { id: 'usr_1782748019419', name: 'Rafael Rodrigues', role: 'monitoramento', username: 'g1078', password: 'Ambev10' },
  { id: 'usr_1784294627000', name: 'José Marcos', role: 'financeiro', username: 'g1006', password: 'Ambev10' },
  { id: 'usr_1', name: 'Alice Conferente', role: 'conferente', username: 'conferente1', password: '123' },
  { id: 'usr_2', name: 'Bruno Fiscal', role: 'auxiliar_logistica', username: 'auxiliar1', password: '123' },
  { id: 'usr_3', name: 'Elisson Minervino', role: 'gestor', username: 'gestor1', password: '123' },
  { id: 'usr_4', name: 'Carlos Motorista', role: 'conferente', username: 'motorista1', password: '123' },
  { id: 'usr_5', name: 'Daniel Monitoramento', role: 'monitoramento', username: 'monitor1', password: '123' }
];
